# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rubocop-stamped 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rubocop-stamped".freeze
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Stamped".freeze]
  s.date = "2018-04-23"
  s.description = "Code style checking for Stamped Ruby repositories, based on RuboCop".freeze
  s.email = "engineering@stamped.ai".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "config/default.yml",
    "config/rails.yml",
    "config/rspec.yml",
    "lib/rubocop-stamped.rb",
    "rubocop-stamped.gemspec"
  ]
  s.homepage = "http://github.com/stampedai/rubocop-stamped".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.6".freeze
  s.summary = "Code style checking for Stamped Ruby repositories".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubocop>.freeze, ["~> 0.52"])
      s.add_runtime_dependency(%q<rubocop-github>.freeze, ["~> 0.10"])
      s.add_runtime_dependency(%q<rubocop-airbnb>.freeze, ["~> 1.0"])
      s.add_runtime_dependency(%q<rubocop-rspec>.freeze, ["~> 1.22"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rubocop>.freeze, ["~> 0.52"])
      s.add_dependency(%q<rubocop-github>.freeze, ["~> 0.10"])
      s.add_dependency(%q<rubocop-airbnb>.freeze, ["~> 1.0"])
      s.add_dependency(%q<rubocop-rspec>.freeze, ["~> 1.22"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rubocop>.freeze, ["~> 0.52"])
    s.add_dependency(%q<rubocop-github>.freeze, ["~> 0.10"])
    s.add_dependency(%q<rubocop-airbnb>.freeze, ["~> 1.0"])
    s.add_dependency(%q<rubocop-rspec>.freeze, ["~> 1.22"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

